const express=require("express");
const path=require('path');
const isauth=require('../middleware/adminauthentication');
const router=express.Router();
const admincontroller=require("../Control/admin");
router.get("/addmembers/",isauth,admincontroller.add);
router.post("/addmembers/",isauth,admincontroller.addmembers);
router.get("/deletemembers/",isauth,admincontroller.delete);
router.post("/search/",isauth,admincontroller.search);
router.post("/delete/",isauth,admincontroller.deletemembers);
router.get("/admincomplaints/",isauth,admincontroller.getcomplaints);
router.get("/escalatecomplaints/",isauth,admincontroller.escalate);
router.post("/escalatecomplaints/",admincontroller.escalateforward);
router.get("/reopencomplaints/",isauth,admincontroller.reopen);
router.post("/reopencomplaints/",isauth,admincontroller.reopenforward);
router.post("/forward/",isauth,admincontroller.forward);
router.get("/adminlogin/",admincontroller.login);
router.get("/adminlogout/",admincontroller.logout);
router.post("/adminlogin/",admincontroller.logins);
 router.post("/admindetails/",isauth,admincontroller.detailsection);
module.exports=router;