const express=require("express");
const path=require('path');
const router=express.Router();
const isauth =require('../middleware/authentication');
const Studentcontroller=require("../Control/Student");

router.get("/studentsignin/",Studentcontroller.studentsignin);
router.post("/studentsignin/",Studentcontroller.signininsert);
router.get("/studentlogin/",Studentcontroller.studentlogin);
router.post("/studentlogin/",Studentcontroller.login);
router.get("/studentdashboard/",isauth,Studentcontroller.studentdashboard);
router.get("/registercomplaint/",isauth,Studentcontroller.registercomplaint);
router.post("/registercomplaint/",isauth,Studentcontroller.register);
router.get("/logout/",Studentcontroller.logout);
router.get("/status/",isauth,Studentcontroller.status);
router.post("/status/",isauth,Studentcontroller.statuscheck);
router.post("/studentdashboard/",isauth,Studentcontroller.escalation);
router.get("/reportget/:complaintid",isauth,Studentcontroller.openreport);
router.post("/reopen/",isauth,Studentcontroller.reopen);
router.post("/details/",isauth,Studentcontroller.detailsection);
module.exports=router;